### ISSUE TITLE
Hokusai pipeline gitdiff / gitlog do not always resolve git-SHA1 tags correctly

### ISSUE THREAD

**Issue by izakp** [artsy/hokusai#53]
Ran into the situation when running `hokusai pipeline [gitdiff/gitlog]` that Hokusai did not correctly resolve the `staging` and `production` tags to git-SHA1 tags:

```
$ hokusai pipeline gitlog -v
==> hokusai exec `kubectl --context staging get deployment --selector app=waves,layer=application -o json`
==> hokusai exec `kubectl --context production get deployment --selector app=waves,layer=application -o json`
Comparing staging to 91dcb5fcf4f58984636a0d85d3573f0e66cb27e5
==> hokusai exec `git log --right-only staging..91dcb5fcf4f58984636a0d85d3573f0e66cb27e5`
fatal: ambiguous argument 'staging..91dcb5fcf4f58984636a0d85d3573f0e66cb27e5': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/hokusai/lib/command.py", line 12, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/hokusai/commands/gitlog.py", line 31, in gitlog
    shout("git log --right-only %s..%s" % (production_tag, staging_tag), print_output=True)
  File "/Library/Python/2.7/site-packages/hokusai/lib/common.py", line 55, in shout
    return check_call(verbose(command), stderr=STDOUT, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'git log --right-only staging..91dcb5fcf4f58984636a0d85d3573f0e66cb27e5' returned non-zero exit status 128
```

The output of `hokusai registry images` was, in this moment:

```
$ hokusai registry images

Image Pushed At           | Image Digest                                                     | Image Tags
-------------------------------------------------------------------------------------------------------------------------------
2018-02-22 23:31:20+01:00 | 3d4e72c8c587fc186a6727862e57463273f6a0d600bedfbb7685e34aa67aefb9 | staging, staging--2018-02-22--22-31-35, latest, 91dcb5fcf4f58984636a0d85d3573f0e66cb27e5
2018-02-21 20:23:49+01:00 | 60487d579f3263fa314273f4334719e374ed04982a50eeb7dde396088e3b0523 | staging--2018-02-21--19-29-19, f0fc132bb4845e784dfd8b59ec4913473a70060d
2018-02-21 20:20:19+01:00 | a99eb51d854ab8617d7615a967779e6886c7a0d9d325d7fb17a07daac3917a52 | bc22372c6f09587b6467ae8ab29dc3d9eefec1ec, staging--2018-02-21--19-27-47
2018-02-19 15:44:44+01:00 | c90af0ae16184575accbf6dacd1b585b354b981fad89bdebc68383116976a34d | staging--2018-02-19--14-45-00, e46b577c70c4fc802020231fab8168e5918ee33a
2018-02-19 15:24:58+01:00 | 3b0a53b5939603defaf4be1b85a2fa4a4a43c333897da127dc86ffb6415ecdab | 0d88e0ce6430acfe5554fb40c0b963f715f76fed, staging--2018-02-19--14-25-15
2018-02-16 23:06:39+01:00 | abedd9bea0ab11751fee6c2ef3ec54020c3a6f77a118f51247b8a4fac9458ffb | staging--2018-02-16--22-07-12, 9fbf5db32456d376f1e3c3db629ff8c7c7db5dff
2018-02-15 19:34:49+01:00 | 6a26dd19d1044704491f4b3995c7768a8c4379e54895bdbe0eaf19ac14226532 | staging--2018-02-15--18-35-09, 91c0fb57405040d20be438a98bb809e1f0bf1a7a
2018-02-13 18:45:13+01:00 | 41a41e2c3a60a41abcfb99488e7e499e1931eba9b0faecb7993679755b49270e | production, production--2018-02-15--17-47-31, staging--2018-02-13--17-45-32, 29c52eea8becf897bf6e3a1908f3de6809dc0563
2018-02-13 18:25:37+01:00 | da14309f7695ece3c7ea293016b59cd89b26c4c12cb6de7a00a13e52cc42e92c | staging--2018-02-13--17-25-55, eb2977f867381455e0fef4d6ab2508cebff04394
2018-02-09 19:54:38+01:00 | 726be8795f2d482a04dcc2143ffd64d2b975f0d5cf87b796c2ac81d16dd7dad9 | 6b8a71bf4eb1e6bc456237668fe15739440c8357, staging--2018-02-09--18-54-56
2018-02-09 18:43:46+01:00 | 50de06a048ab78a0d545f619ea8a1469f553944ac5ef7a4b1956f88542345d0a | d471dbd041c58314fa6f268502507081affab6d0
```

**Comment by izakp** [comment]
Fixed via https://github.com/artsy/hokusai/pull/80
